name: Bump Version

on: 
  workflow_dispatch:
    inputs:
      versioning_type:
        description: 'Semantic Versioning Type (major/minor/patch)'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git config --global user.email "${{ github.actor }}[bot]@users.noreply.github.com"
      - run: git config --global user.name "${{ github.actor }}[bot]"
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: npm version ${{ inputs.versioning_type }}
      - name: Push commit
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: "main"
          tags: true
